const GLYPHS={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
const VALUES={p:1,n:3,b:3,r:5,q:9,k:0};
const $=s=>document.querySelector(s);
let state, selected=null, legal=[], history=[], pendingPromotion=null;
let mode='local', level='easy', myColor='w', room=null, roomToken=null, roomVersion=0, pollTimer=null, thinking=false;
let currentLang='he';
let lessonIndex=0;
let tutorialSelected=false,tutorialPieces=null,tutorialDone=false,tutorialFeedback='';
const LESSONS=[
 {he:['המלך ומטרת המשחק','המלך זז משבצת אחת בלבד לכל כיוון: קדימה, אחורה, לצדדים או באלכסון. כאשר מאיימים עליו הוא בשח. אם אין דרך בטוחה לברוח ואי אפשר לחסום או ללכוד את התוקף — זה מט.'],en:['The king and the goal','The king moves one square in any direction: forward, backward, sideways, or diagonally. If it is attacked with no safe escape, block, or capture — it is checkmate.'],pieces:[[7,4,'w','k'],[0,4,'b','k']],hints:[[6,3],[6,4],[6,5],[7,3],[7,5]],focus:[[7,4]]},
 {he:['איך החייל זז','החייל מתקדם משבצת אחת קדימה. במהלך הראשון שלו הוא יכול להתקדם שתי משבצות.'],en:['How the pawn moves','A pawn moves one square forward. On its first move it may move two.'],pieces:[[6,4,'w','p']],hints:[[5,4],[4,4]],focus:[[6,4]],target:[4,4]},
 {he:['איך החייל אוכל','החייל זז ישר קדימה, אבל אוכל משבצת אחת באלכסון קדימה. כאן אפשר לאכול את הפרש או את הרץ.'],en:['How the pawn captures','A pawn moves straight forward, but captures one square diagonally forward. Here it may capture either piece.'],pieces:[[4,4,'w','p'],[3,3,'b','n'],[3,5,'b','b']],hints:[[3,3],[3,5]],focus:[[4,4]]},
 {he:['הכתרת חייל','כשחייל מגיע לשורה האחרונה בצד של היריב הוא מוכתר. אפשר להחליף אותו במלכה, צריח, רץ או פרש — בדרך כלל בוחרים מלכה. אי אפשר לבחור מלך או חייל נוסף.'],en:['Pawn promotion','When a pawn reaches the last rank on the opponent’s side, it is promoted. Choose a queen, rook, bishop, or knight — usually a queen.'],pieces:[[1,4,'w','p']],hints:[[0,4]],focus:[[1,4]],target:[0,4],promotion:'q'},
 {he:['הצריח','הצריח נע בקו ישר למעלה, למטה ולצדדים — והוא יכול לעצור בכל משבצת פנויה בדרך.'],en:['The rook','A rook travels in straight lines and may stop on any clear square along the way.'],pieces:[[4,3,'w','r']],hints:[[0,3],[1,3],[2,3],[3,3],[5,3],[6,3],[7,3],[4,0],[4,1],[4,2],[4,4],[4,5],[4,6],[4,7]],focus:[[4,3]]},
 {he:['הרץ','הרץ נע באלכסון לכל מרחק פנוי. הוא נשאר תמיד על אותו צבע של משבצות ויכול לאכול כלי יריב שנמצא בדרכו.'],en:['The bishop','A bishop moves diagonally for any clear distance. It always stays on the same square color and may capture an enemy in its path.'],pieces:[[5,2,'w','b'],[2,5,'b','r']],hints:[[4,1],[3,0],[4,3],[3,4],[2,5],[6,1],[7,0],[6,3],[7,4]],focus:[[5,2]]},
 {he:['המלכה','המלכה משלבת את תנועת הצריח והרץ: היא נעה בקו ישר או באלכסון עד שכלי חוסם את הדרך. היא יכולה לאכול את הכלי החוסם, אבל לעולם לא לדלג מעליו.'],en:['The queen','The queen combines rook and bishop movement, moving until a piece blocks the path. It may capture that piece, but can never jump over it.'],pieces:[[4,3,'w','q'],[1,3,'b','r'],[4,7,'b','b']],hints:[[1,3],[2,3],[3,3],[5,3],[6,3],[7,3],[4,0],[4,1],[4,2],[4,4],[4,5],[4,6],[4,7],[0,7],[1,6],[2,5],[3,4],[3,2],[2,1],[1,0],[5,2],[6,1],[7,0],[5,4],[6,5],[7,6]],focus:[[4,3]]},
 {he:['הפרש','הפרש נע בצורת ר׳: שתי משבצות בכיוון אחד ואז אחת הצידה. הוא יכול לקפוץ מעל כלים ולאכול כלי יריב שנמצא במשבצת הנחיתה.'],en:['The knight','A knight moves in an L shape: two squares one way and one sideways. It can jump over pieces and capture an enemy on its landing square.'],pieces:[[4,4,'w','n'],[2,5,'b','b'],[5,2,'b','r']],hints:[[2,3],[2,5],[3,2],[3,6],[5,2],[5,6],[6,3],[6,5]],focus:[[4,4]]},
 {he:['שח ומט','כשהמלך מותקף הוא בשח. אם אין מהלך חוקי שמציל אותו — זה מט והמשחק נגמר.'],en:['Checkmate','When a king is attacked it is in check. If no legal move saves it, the game ends.'],pieces:[[0,7,'b','k'],[1,6,'w','q'],[2,5,'w','k']],focus:[[0,7]]}
];
const TASKS={he:[['לחץ על המלך הלבן המסומן.','בחר אחת מהנקודות והזז את המלך משבצת אחת לכל כיוון.'],['לחץ על החייל המסומן.','זה המהלך הראשון שלו: הזז אותו שתי משבצות ישר קדימה בעזרת הנקודות.'],['לחץ על החייל הלבן.','בחר בעזרת הנקודות ואכול את הפרש או את הרץ באלכסון קדימה.'],['לחץ על החייל שנמצא ליד סוף הלוח.','הזז אותו לשורה האחרונה ובחר כלי להכתרה.'],['לחץ על הצריח המסומן.','בחר נקודה והזז את הצריח בקו ישר.'],['לחץ על הרץ המסומן.','הזז את הרץ באלכסון. אפשר גם לאכול את הצריח השחור.'],['לחץ על המלכה המסומנת.','הזז אותה בקו ישר או באלכסון. אפשר לאכול את אחד הכלים השחורים.'],['לחץ על הפרש המסומן.','הזז אותו שתי משבצות למעלה ואחת ימינה.'],null],en:[['Click the highlighted white king.','Use the dots to move the king one square in any direction.'],['Click the highlighted pawn.','This is its first move: move it two squares straight forward using the dots.'],['Click the white pawn.','Use the dots to capture either piece diagonally.'],['Click the pawn near the end.','Move it to the last rank and choose a promotion piece.'],['Click the highlighted rook.','Choose a dot and move it in a straight line.'],['Click the highlighted bishop.','Move it diagonally. You may also capture the black rook.'],['Click the highlighted queen.','Move straight or diagonally. You may capture either black piece.'],['Click the highlighted knight.','Move it two squares up and one right.'],null]};
const WORDS={he:{turn:'תור ה',white:'לבן',black:'שחור',move:'מהלך',check:' — שח',sure:'המשחק עדיין בעיצומו. האם אתה בטוח שאתה רוצה לצאת לתפריט הראשי?'},en:{turn:'Turn: ',white:'White',black:'Black',move:'Move',check:' — Check',sure:'The game is still in progress. Are you sure you want to return to the main menu?'}};
const tr=k=>WORDS[currentLang][k];

function initialBoard(){
  const b=Array.from({length:8},()=>Array(8).fill(null)), back=['r','n','b','q','k','b','n','r'];
  for(let c=0;c<8;c++){ b[0][c]={c:'b',t:back[c]}; b[1][c]={c:'b',t:'p'}; b[6][c]={c:'w',t:'p'}; b[7][c]={c:'w',t:back[c]}; }
  return b;
}
function newGame(){ state={board:initialBoard(),turn:'w',castling:{wk:1,wq:1,bk:1,bq:1},ep:null,half:0,full:1,last:null,captured:[],over:false}; history=[]; selected=null; legal=[]; render(); }
function saveGame(){if(!state||!history.length)return;localStorage.setItem('chess-saved-game',JSON.stringify({state,history,mode,level,myColor,room,roomToken,label:$('#mode-label').textContent}));updateContinue();}
function updateContinue(){const raw=localStorage.getItem('chess-saved-game');$('#continue-game').classList.toggle('hidden',!raw);if(raw)try{$('#continue-label').textContent=JSON.parse(raw).label||'חזרה למשחק השמור';}catch(e){}}
function applyAppearance(piece='carved',board='wood'){[...document.body.classList].filter(x=>x.startsWith('pieces-')||x.startsWith('board-')).forEach(x=>document.body.classList.remove(x));document.body.classList.add(`pieces-${piece}`,`board-${board}`);localStorage.setItem('chess-appearance',JSON.stringify({piece,board}));document.querySelectorAll('#piece-styles button').forEach(b=>b.classList.toggle('active',b.dataset.style===piece));document.querySelectorAll('#board-styles button').forEach(b=>b.classList.toggle('active',b.dataset.style===board));}
function loadAppearance(){try{const x=JSON.parse(localStorage.getItem('chess-appearance'))||{};applyAppearance(x.piece||'carved',x.board||'wood');}catch(e){applyAppearance();}}
function applyLanguage(lang){
  currentLang=lang;localStorage.setItem('chess-language',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';
  const en=lang==='en',set=(s,v,html=false)=>{const e=$(s);if(e)e[html?'innerHTML':'textContent']=v;};
  set('.lobby-copy .eyebrow',en?'WELCOME':'ברוכים הבאים');set('.lobby-copy h2',en?'How will you<br><em>play today?</em>':'איך משחקים<br><em>היום?</em>',true);set('.lobby-copy>p:last-child',en?'Choose an opponent, set the pieces — and begin.':'בחרו יריב, הכינו את הכלים — וצאו לדרך.');
  set('#computer-mode strong',en?'Play the computer':'נגד המחשב');set('#computer-mode small',en?'Choose a level and play now':'בחרו רמה ושחקו מיד');set('#friend-mode strong',en?'Play a friend':'משחק עם חבר');set('#friend-mode small',en?'Create a room and share its code':'צרו חדר ושתפו קוד');set('#continue-game strong',en?'Continue game':'המשך משחק');set('.lobby-settings span',en?'Settings':'הגדרות');
  set('#learn-mode strong',en?'How to play chess':'איך משחקים שחמט');set('#learn-mode small',en?'Learn with a demonstration board':'למדו בעזרת לוח הדגמה');set('#lesson-prev',en?'Previous':'הקודם');
  set('#computer-panel h3',en?'Choose difficulty':'בחרו רמת קושי');set('#friend-panel h3',en?'Play a friend':'משחק עם חבר');set('#create-room',en?'Create a new room':'צור חדר חדש');set('.divider span',en?'or join with a code':'או הצטרפו עם קוד');set('#join-form button',en?'Join':'הצטרף');$('#room-input').placeholder=en?'GAME CODE':'קוד משחק';
  set('#new-game',en?'Main menu <span>↗</span>':'לתפריט הראשי <span>↗</span>',true);set('#undo',en?'↶&nbsp;&nbsp;Undo move':'↶&nbsp;&nbsp;בטל מהלך',true);set('.player-white strong',tr('white'));set('.player-black strong',tr('black'));set('h1',en?'Your<br><em>move.</em>':'המהלך<br><em>שלך.</em>',true);
  set('.settings-card>.eyebrow',en?'PERSONALIZE':'התאמה אישית');set('#settings-title',en?'Design settings':'הגדרות עיצוב');const labels=document.querySelectorAll('.settings-card>label');if(labels[0])labels[0].textContent=en?'Piece style':'סגנון הכלים';if(labels[1])labels[1].textContent=en?'Board style':'סגנון הלוח';set('#language-label',en?'Language':'שפה');
  const names=en?['Carved','8-bit','Neon','Caramel','Ice','Candy','Paper','Shadows','Natural wood','Club','Night','Marble','Ocean','Candy','Desert','Monochrome']:['מגולף','8־ביט','ניאון','קרמל','קרח','סוכריות','נייר','צללים','עץ טבעי','מועדון','לילה','שיש','אוקיינוס','ממתקים','מדבר','מונוכרום'];document.querySelectorAll('.style-options strong').forEach((x,i)=>x.textContent=names[i]);document.querySelectorAll('.levels button').forEach((b,i)=>b.textContent=(en?['Easy','Medium','Hard']:['קל','בינוני','קשה'])[i]);document.querySelectorAll('#language-options button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderLesson();if(state)render();
}
function resumeGame(){try{const x=JSON.parse(localStorage.getItem('chess-saved-game'));state=x.state;history=x.history||[];mode=x.mode||'local';level=x.level||'easy';myColor=x.myColor||'w';room=x.room;roomToken=x.roomToken;selected=null;legal=[];$('#mode-label').textContent=x.label||'משחק שמור';$('#lobby').classList.add('hidden');$('.app').classList.remove('hidden');render();if(mode==='online'&&room)pollTimer=setInterval(pollRoom,900);if(mode==='computer'&&state.turn==='b')setTimeout(computerMove,380);}catch(e){localStorage.removeItem('chess-saved-game');updateContinue();}}
function clone(x){return JSON.parse(JSON.stringify(x));}
function inBounds(r,c){return r>=0&&r<8&&c>=0&&c<8;}
function rawMoves(s,r,c,attacks=false){
  const p=s.board[r][c]; if(!p)return []; const out=[], add=(rr,cc,special)=>{if(inBounds(rr,cc)&&(!s.board[rr][cc]||s.board[rr][cc].c!==p.c))out.push({r:rr,c:cc,special});};
  if(p.t==='p'){
    const d=p.c==='w'?-1:1,start=p.c==='w'?6:1;
    if(!attacks&&!s.board[r+d]?.[c]){add(r+d,c);if(r===start&&!s.board[r+2*d][c])add(r+2*d,c,'double');}
    for(const dc of[-1,1]){const rr=r+d,cc=c+dc;if(attacks&&inBounds(rr,cc))out.push({r:rr,c:cc});else if(inBounds(rr,cc)&&(s.board[rr][cc]?.c!==p.c&&s.board[rr][cc]||s.ep?.r===rr&&s.ep?.c===cc))add(rr,cc,s.ep?.r===rr&&s.ep?.c===cc?'ep':undefined);}
  } else if(p.t==='n') for(const [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);
  else if(p.t==='k'){
    for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);
    if(!attacks&&!isCheck(s,p.c)){
      const row=p.c==='w'?7:0, enemy=p.c==='w'?'b':'w';
      if(r===row&&c===4&&s.castling[p.c+'k']&&!s.board[row][5]&&!s.board[row][6]&&!attacked(s,row,5,enemy)&&!attacked(s,row,6,enemy))out.push({r:row,c:6,special:'castleK'});
      if(r===row&&c===4&&s.castling[p.c+'q']&&!s.board[row][1]&&!s.board[row][2]&&!s.board[row][3]&&!attacked(s,row,3,enemy)&&!attacked(s,row,2,enemy))out.push({r:row,c:2,special:'castleQ'});
    }
  } else {
    const dirs=p.t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:p.t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];
    for(const [dr,dc] of dirs){let rr=r+dr,cc=c+dc;while(inBounds(rr,cc)){if(!s.board[rr][cc])out.push({r:rr,c:cc});else{if(s.board[rr][cc].c!==p.c)out.push({r:rr,c:cc});break;}rr+=dr;cc+=dc;}}
  } return out;
}
function attacked(s,r,c,by){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++){const p=s.board[rr][cc];if(p?.c===by&&rawMoves(s,rr,cc,true).some(m=>m.r===r&&m.c===c))return true;}return false;}
function isCheck(s,color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]?.c===color&&s.board[r][c].t==='k')return attacked(s,r,c,color==='w'?'b':'w');return false;}
function applyMove(s,from,m,promo='q'){
  const n=clone(s),p=n.board[from.r][from.c],target=n.board[m.r][m.c]; if(target)n.captured.push(target);
  n.board[m.r][m.c]=p;n.board[from.r][from.c]=null;
  if(m.special==='ep'){const cr=m.r+(p.c==='w'?1:-1);n.captured.push(n.board[cr][m.c]);n.board[cr][m.c]=null;}
  if(m.special==='castleK'){n.board[m.r][5]=n.board[m.r][7];n.board[m.r][7]=null;}
  if(m.special==='castleQ'){n.board[m.r][3]=n.board[m.r][0];n.board[m.r][0]=null;}
  if(p.t==='p'&&(m.r===0||m.r===7))p.t=promo;
  if(p.t==='k'){n.castling[p.c+'k']=0;n.castling[p.c+'q']=0;}
  if(p.t==='r'){if(from.r===7&&from.c===0)n.castling.wq=0;if(from.r===7&&from.c===7)n.castling.wk=0;if(from.r===0&&from.c===0)n.castling.bq=0;if(from.r===0&&from.c===7)n.castling.bk=0;}
  if(target?.t==='r'){if(m.r===7&&m.c===0)n.castling.wq=0;if(m.r===7&&m.c===7)n.castling.wk=0;if(m.r===0&&m.c===0)n.castling.bq=0;if(m.r===0&&m.c===7)n.castling.bk=0;}
  n.ep=m.special==='double'?{r:(from.r+m.r)/2,c:m.c}:null;n.last={from,to:{r:m.r,c:m.c}};n.turn=p.c==='w'?'b':'w';if(n.turn==='w')n.full++;return n;
}
function validMoves(s,r,c){const p=s.board[r][c];if(!p)return[];return rawMoves(s,r,c).filter(m=>!isCheck(applyMove(s,{r,c},m),p.c));}
function allMoves(s,color){const a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]?.c===color)for(const m of validMoves(s,r,c))a.push(m);return a;}
function clickSquare(r,c){
  if(state.over||thinking||(mode==='computer'&&state.turn==='b')||(mode==='online'&&state.turn!==myColor))return; const p=state.board[r][c];
  if(selected){const move=legal.find(m=>m.r===r&&m.c===c);if(move){const moving=state.board[selected.r][selected.c];if(moving.t==='p'&&(r===0||r===7)){pendingPromotion={from:selected,move,color:moving.c};showPromotion(moving.c);return;}commit(selected,move);return;}}
  if(p?.c===state.turn){selected={r,c};legal=validMoves(state,r,c);}else{selected=null;legal=[];}render();
}
function playMoveSound(capture=false){
  try{const ctx=new (window.AudioContext||window.webkitAudioContext)(),now=ctx.currentTime,gain=ctx.createGain(),osc=ctx.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(capture?150:210,now);osc.frequency.exponentialRampToValueAtTime(85,now+.09);gain.gain.setValueAtTime(.12,now);gain.gain.exponentialRampToValueAtTime(.001,now+.11);osc.connect(gain).connect(ctx.destination);osc.start(now);osc.stop(now+.12);osc.onended=()=>ctx.close();}catch(e){}
}
function commit(from,move,promo){
  const squares=$('#board').children,fromEl=squares[from.r*8+from.c],toEl=squares[move.r*8+move.c],piece=state.board[from.r][from.c],capture=!!state.board[move.r][move.c]||move.special==='ep';
  const finish=()=>{history.push(clone(state));state=applyMove(state,from,move,promo);selected=null;legal=[];thinking=false;finishTurn();render();saveGame();playMoveSound(capture);if(mode==='computer'&&!state.over&&state.turn==='b')setTimeout(computerMove,380);if(mode==='online')sendState();};
  if(!fromEl||!toEl||!piece){finish();return;}
  thinking=true;const a=fromEl.getBoundingClientRect(),b=toEl.getBoundingClientRect(),fly=document.createElement('span');
  fly.className=`piece flying-piece ${piece.c==='b'?'black':''}`;fly.textContent=GLYPHS[piece.c][piece.t];fly.style.cssText=`left:${a.left}px;top:${a.top}px;width:${a.width}px;height:${a.height}px;`;
  fromEl.querySelector('.piece')?.classList.add('piece-hidden');document.body.appendChild(fly);
  requestAnimationFrame(()=>requestAnimationFrame(()=>fly.style.transform=`translate(${b.left-a.left}px,${b.top-a.top}px)`));
  setTimeout(()=>{fly.remove();finish();},260);
}
function finishTurn(){const moves=allMoves(state,state.turn),check=isCheck(state,state.turn);if(!moves.length){state.over=true;state.result=check?(state.turn==='w'?'השחור ניצח במט':'הלבן ניצח במט'):'תיקו — פט';}else if(insufficient()) {state.over=true;state.result='תיקו — אין מספיק כלים למט';}}
function insufficient(){const pieces=state.board.flat().filter(p=>p&&p.t!=='k');return pieces.length===0||(pieces.length===1&&['b','n'].includes(pieces[0].t));}
function showPromotion(color){const box=$('#promotion-options');box.innerHTML='';for(const t of['q','r','b','n']){const b=document.createElement('button');b.textContent=GLYPHS[color][t];b.onclick=()=>{$('#promotion').classList.add('hidden');commit(pendingPromotion.from,pendingPromotion.move,t);pendingPromotion=null;};box.appendChild(b);}$('#promotion').classList.remove('hidden');}
function render(){
  const board=$('#board');board.innerHTML='';const checked=isCheck(state,state.turn);
  for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=document.createElement('button'),p=state.board[r][c],isLegal=legal.some(m=>m.r===r&&m.c===c);sq.className='square '+((r+c)%2?'dark':'');if(selected?.r===r&&selected?.c===c)sq.classList.add('selected');if(state.last&&(state.last.from.r===r&&state.last.from.c===c||state.last.to.r===r&&state.last.to.c===c))sq.classList.add('last');if(isLegal){sq.classList.add('legal');if(p)sq.classList.add('capture');}if(checked&&p?.c===state.turn&&p.t==='k')sq.classList.add('check');sq.onclick=()=>clickSquare(r,c);sq.setAttribute('aria-label',`${String.fromCharCode(97+c)}${8-r}${p?' '+p.t:''}`);if(p)sq.innerHTML=`<span class="piece ${p.c==='b'?'black':''}">${GLYPHS[p.c][p.t]}</span>`;if(c===0)sq.innerHTML+=`<span class="coord rank">${8-r}</span>`;if(r===7)sq.innerHTML+=`<span class="coord file">${String.fromCharCode(97+c)}</span>`;board.appendChild(sq);}
  const check=checked?tr('check'):'';$('#status').textContent=state.over?state.result:`${tr('turn')}${state.turn==='w'?tr('white'):tr('black')}${check}`;$('#move-count').textContent=`${tr('move')} ${state.full}`;$('#white-turn').classList.toggle('on',state.turn==='w'&&!state.over);$('#black-turn').classList.toggle('on',state.turn==='b'&&!state.over);$('#undo').disabled=!history.length;
  const caps=color=>state.captured.filter(p=>p.c===color).sort((a,b)=>VALUES[b.t]-VALUES[a.t]).map(p=>GLYPHS[p.c][p.t]).join('');$('#white-captures').textContent=caps('b');$('#black-captures').textContent=caps('w');
}
function startGame(kind,label){localStorage.removeItem('chess-saved-game');mode=kind;newGame();$('#mode-label').textContent=label;$('#lobby').classList.add('hidden');$('.app').classList.remove('hidden');updateContinue();}
function showPanel(id){$('.mode-cards').classList.add('hidden');document.querySelectorAll('.setup-panel').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');}
function renderLesson(){const board=$('#tutorial-board');if(!board)return;const x=LESSONS[lessonIndex],copy=x[currentLang]||x.he,pieces=tutorialPieces||x.pieces,task=TASKS[currentLang][lessonIndex],mover=pieces[0],hints=tutorialDone?tutorialLegalMoves(mover,pieces):(x.hints||[]),focus=tutorialDone?[[mover[0],mover[1]]]:(x.focus||[]);let instruction=task?(tutorialDone?(currentLang==='en'?'✓ Great move! Keep practicing or press Next.':'✓ מהלך מצוין! אפשר להמשיך לתרגל או ללחוץ על הבא.'):task[tutorialSelected?1:0]):'';if(tutorialFeedback)instruction=tutorialFeedback;$('#lesson-title').textContent=copy[0];$('#lesson-text').textContent=copy[1]+(instruction?' '+instruction:'');$('#lesson-count').textContent=`${currentLang==='en'?'LESSON':'שיעור'} ${lessonIndex+1} / ${LESSONS.length}`;board.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('button'),p=pieces.find(q=>q[0]===r&&q[1]===c);s.className=`tutorial-square ${(r+c)%2?'dark':''}`;if(tutorialSelected&&hints.some(q=>q[0]===r&&q[1]===c))s.classList.add('hint');if(focus.some(q=>q[0]===r&&q[1]===c))s.classList.add('focus');if(p)s.innerHTML=`<span class="tutorial-piece ${p[2]==='b'?'black':''}">${GLYPHS[p[2]][p[3]]}</span>`;s.onclick=()=>tutorialClick(r,c);board.appendChild(s);}$('#lesson-prev').disabled=lessonIndex===0;$('#lesson-next').textContent=lessonIndex===LESSONS.length-1?(currentLang==='en'?'Finish':'סיום'):(currentLang==='en'?'Next':'הבא');}
function animateTutorialMove(from,to,piece,done){const squares=$('#tutorial-board').children,aEl=squares[from[0]*8+from[1]],bEl=squares[to[0]*8+to[1]];if(!aEl||!bEl){done();return;}const a=aEl.getBoundingClientRect(),b=bEl.getBoundingClientRect(),fly=document.createElement('span');fly.className=`tutorial-piece tutorial-flying ${piece[2]==='b'?'black':''}`;fly.textContent=GLYPHS[piece[2]][piece[3]];fly.style.cssText=`left:${a.left}px;top:${a.top}px;width:${a.width}px;height:${a.height}px;`;aEl.querySelector('.tutorial-piece').style.opacity='0';document.body.appendChild(fly);requestAnimationFrame(()=>requestAnimationFrame(()=>fly.style.transform=`translate(${b.left-a.left}px,${b.top-a.top}px)`));setTimeout(()=>{fly.remove();done();},280);}
function chooseTutorialPromotion(pieces,moving){const box=$('#promotion-options');box.innerHTML='';$('#promotion .modal-card p').textContent=currentLang==='en'?'Choose a promotion piece':'בחר כלי להכתרת החייל';for(const t of['q','r','b','n']){const b=document.createElement('button');b.textContent=GLYPHS[moving[2]][t];b.onclick=()=>{moving[3]=t;tutorialPieces=pieces;tutorialDone=true;tutorialFeedback='';$('#promotion').classList.add('hidden');playMoveSound(false);renderLesson();};box.appendChild(b);}$('#promotion').classList.remove('hidden');}
function tutorialLegalMoves(piece,pieces){const [r,c,,t]=piece,out=[],occupied=(rr,cc)=>pieces.find(p=>p[0]===rr&&p[1]===cc),add=(rr,cc)=>{if(inBounds(rr,cc)&&(!occupied(rr,cc)||occupied(rr,cc)[2]!==piece[2]))out.push([rr,cc]);};if(t==='p'){const d=piece[2]==='w'?-1:1;if(!occupied(r+d,c))add(r+d,c);for(const dc of[-1,1])if(occupied(r+d,c+dc)?.[2]!==piece[2]&&occupied(r+d,c+dc))add(r+d,c+dc);}else if(t==='n'){for(const [dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);}else if(t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);}else{const dirs=t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(inBounds(rr,cc)){add(rr,cc);if(occupied(rr,cc))break;rr+=dr;cc+=dc;}}}return out;}
function tutorialClick(r,c){const x=LESSONS[lessonIndex],pieces=JSON.parse(JSON.stringify(tutorialPieces||x.pieces));if(!x.hints?.length)return;const mover=pieces[0],focus=tutorialDone?[[mover[0],mover[1]]]:(x.focus||[]),hints=tutorialDone?tutorialLegalMoves(mover,pieces):(x.hints||[]);if(!tutorialSelected){if(focus.some(q=>q[0]===r&&q[1]===c)){tutorialSelected=true;tutorialFeedback='';renderLesson();}return;}if(hints.some(q=>q[0]===r&&q[1]===c)){if(!tutorialDone&&x.target&&(r!==x.target[0]||c!==x.target[1])){tutorialFeedback=currentLang==='en'?'Almost — follow the instruction above.':'כמעט — בצע את ההוראה שמעל הלוח.';renderLesson();return;}tutorialSelected=false;const from=[mover[0],mover[1]],wasCapture=pieces.some((p,j)=>j>0&&p[0]===r&&p[1]===c);animateTutorialMove(from,[r,c],mover,()=>{mover[0]=r;mover[1]=c;const finalPieces=pieces.filter((p,j)=>j===0||p[0]!==r||p[1]!==c);if(x.promotion&&mover[3]==='p'&&(r===0||r===7)){chooseTutorialPromotion(finalPieces,mover);return;}tutorialPieces=finalPieces;tutorialDone=true;tutorialFeedback='';playMoveSound(wasCapture);renderLesson();});}}
function computerMove(){
  if(state.over||state.turn!=='b')return;thinking=true;render();const choices=[];
  for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(state.board[r][c]?.c==='b')for(const m of validMoves(state,r,c)){let score=state.board[m.r][m.c]?VALUES[state.board[m.r][m.c].t]*10:0;const next=applyMove(state,{r,c},m);if(isCheck(next,'w'))score+=3;if(level==='hard'){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++)if(next.board[rr][cc]?.c==='w')for(const reply of validMoves(next,rr,cc))score-=next.board[reply.r][reply.c]?VALUES[next.board[reply.r][reply.c].t]*6:0;}choices.push({from:{r,c},m,score:score+Math.random()*(level==='easy'?30:level==='medium'?8:2)});}
  choices.sort((a,b)=>b.score-a.score);thinking=false;if(choices[0])commit(choices[0].from,choices[0].m);
}
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||'שגיאה בחיבור');return data;}
async function createRoom(){try{const x=await api('/api/rooms',{method:'POST',body:'{}'});room=x.code;roomToken=x.token;myColor='w';roomVersion=0;$('#room-code').textContent=room;showPanel('#waiting-panel');pollTimer=setInterval(pollRoom,900);}catch(e){$('#room-error').textContent='צריך להפעיל את שרת המשחק החדש';}}
async function joinRoom(ev){ev.preventDefault();const code=$('#room-input').value.trim().toUpperCase();if(code.length!==6){$('#room-error').textContent='יש להזין קוד בן 6 תווים';return;}try{const x=await api(`/api/rooms/${code}/join`,{method:'POST',body:'{}'});room=code;roomToken=x.token;myColor='b';startGame('online',`משחק אונליין · חדר ${room}`);pollTimer=setInterval(pollRoom,900);}catch(e){$('#room-error').textContent=e.message;}}
async function pollRoom(){if(!room)return;try{const x=await api(`/api/rooms/${room}`);if(x.ready&&mode!=='online'){startGame('online',`משחק אונליין · חדר ${room}`);await sendState();}else if(mode==='online'&&x.state&&x.version>roomVersion){state=x.state;roomVersion=x.version;selected=null;legal=[];finishTurn();render();}}catch(e){}}
async function sendState(){try{const x=await api(`/api/rooms/${room}/state`,{method:'POST',body:JSON.stringify({token:roomToken,state})});roomVersion=x.version;}catch(e){$('#status').textContent=e.message;}}
$('#computer-mode').onclick=()=>showPanel('#computer-panel');$('#friend-mode').onclick=()=>showPanel('#friend-panel');document.querySelectorAll('.back').forEach(b=>b.onclick=()=>{document.querySelectorAll('.setup-panel').forEach(x=>x.classList.add('hidden'));$('.mode-cards').classList.remove('hidden');});
$('#learn-mode').onclick=()=>{lessonIndex=0;tutorialSelected=false;tutorialPieces=null;tutorialDone=false;tutorialFeedback='';showPanel('#learn-panel');renderLesson();};$('#lesson-prev').onclick=()=>{if(lessonIndex>0){lessonIndex--;tutorialSelected=false;tutorialPieces=null;tutorialDone=false;tutorialFeedback='';renderLesson();}};$('#lesson-next').onclick=()=>{if(lessonIndex<LESSONS.length-1){lessonIndex++;tutorialSelected=false;tutorialPieces=null;tutorialDone=false;tutorialFeedback='';renderLesson();}else{document.querySelectorAll('.setup-panel').forEach(x=>x.classList.add('hidden'));$('.mode-cards').classList.remove('hidden');}};
$('#continue-game').onclick=resumeGame;
document.querySelectorAll('.settings-open').forEach(b=>b.onclick=()=>$('#settings').classList.remove('hidden'));$('#close-settings').onclick=()=>$('#settings').classList.add('hidden');$('#settings').onclick=e=>{if(e.target.id==='settings')$('#settings').classList.add('hidden');};
document.querySelectorAll('#piece-styles button').forEach(b=>b.onclick=()=>{const x=JSON.parse(localStorage.getItem('chess-appearance')||'{}');applyAppearance(b.dataset.style,x.board||'wood');});document.querySelectorAll('#board-styles button').forEach(b=>b.onclick=()=>{const x=JSON.parse(localStorage.getItem('chess-appearance')||'{}');applyAppearance(x.piece||'carved',b.dataset.style);});
document.querySelectorAll('#language-options button').forEach(b=>b.onclick=()=>applyLanguage(b.dataset.lang));
document.querySelectorAll('.levels button').forEach(b=>b.onclick=()=>{level=b.dataset.level;const names=currentLang==='en'?{easy:'Easy',medium:'Medium',hard:'Hard'}:{easy:'קל',medium:'בינוני',hard:'קשה'};startGame('computer',`${currentLang==='en'?'Computer':'נגד המחשב'} · ${names[level]}`);});
$('#create-room').onclick=createRoom;$('#join-form').onsubmit=joinRoom;$('#room-input').oninput=e=>e.target.value=e.target.value.replace(/[^a-z0-9]/gi,'').toUpperCase();$('#room-code').onclick=()=>navigator.clipboard?.writeText(room);
$('#new-game').onclick=()=>{
  if(history.length&&!confirm(tr('sure')))return;
  if(pollTimer)clearInterval(pollTimer);room=null;mode='local';$('.app').classList.add('hidden');$('#lobby').classList.remove('hidden');$('.mode-cards').classList.remove('hidden');document.querySelectorAll('.setup-panel').forEach(x=>x.classList.add('hidden'));
};
$('#undo').onclick=()=>{if(history.length){state=history.pop();selected=null;legal=[];render();saveGame();}};
window.addEventListener('beforeunload',saveGame);
const renderLessonBase=renderLesson;renderLesson=function(){renderLessonBase();const b=$('#tutorial-board');if(b)b.classList.toggle('mate-demo',lessonIndex===LESSONS.length-1);};
newGame();updateContinue();loadAppearance();applyLanguage(localStorage.getItem('chess-language')||'he');
